name: amspec-app-v2

services:
  - name: amspec-backend
    github:
      repo: cuellar1992/Amspec-app-ini
      branch: main
      deploy_on_push: true
    # Build command: construir frontend y copiarlo a server/public
    build_command: |
      npm install
      npm run build
      rm -rf server/public
      cp -r dist server/public
      cd server
      npm install
    run_command: cd server && npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    routes:
      - path: /
    envs:
      - key: NODE_VERSION
        value: "18"
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8080"
      - key: MONGODB_URI
        value: ${MONGODB_URI}
      - key: JWT_SECRET
        value: ${JWT_SECRET}
      - key: JWT_REFRESH_SECRET
        value: ${JWT_REFRESH_SECRET}